// Generated by CoffeeScript 1.4.0
(function() {

  window.addEventListener("load", function() {
    var canvas, dataAttr, svg;
    canvas = d3.select("#canvas1");
    svg = canvas.append("svg").attr("width", 200).attr("height", 200);
    dataAttr = [
      {
        key1: 10,
        key2: 10,
        key3: 80,
        key4: 80,
        key5: "green"
      }, {
        key1: 110,
        key2: 110,
        key3: 80,
        key4: 80,
        key5: "blue"
      }
    ];
    svg.append("rect");
    svg.append("rect");
    svg.selectAll("rect").data(dataAttr).attr("x", function(d, i) {
      return d.key1;
    }).attr("y", function(d, i) {
      return d.key2;
    }).attr("width", function(d, i) {
      return d.key3;
    }).attr("height", function(d, i) {
      return d.key4;
    }).attr("fill", function(d, i) {
      return d.key5;
    });
    return svg.selectAll("rect").data(dataAttr).enter().append("rect").attr("x", function(d, i) {
      return d.key1;
    }).attr("y", function(d, i) {
      return d.key2;
    }).attr("width", function(d, i) {
      return d.key3;
    }).attr("height", function(d, i) {
      return d.key4;
    }).attr("fill", function(d, i) {
      return d.key5;
    });
  }, false);

}).call(this);
