// Generated by CoffeeScript 1.3.2-pre
(function() {
  var compose, fn, inv;

  compose = function(f, g) {
    return function(x) {
      return f(g(x));
    };
  };

  fn = [
    Math.sin, Math.cos, function(x) {
      return Math.pow(x, 3);
    }
  ];

  inv = [
    Math.asin, Math.acos, function(x) {
      return Math.pow(x, 1 / 3);
    }
  ];

  (function() {
    var f, i, _i, _results;
    _results = [];
    for (i = _i = 0; _i <= 2; i = ++_i) {
      f = compose(inv[i], fn[i]);
      _results.push(console.log(f(0.5)));
    }
    return _results;
  })();

}).call(this);
