// Generated by CoffeeScript 1.4.0
(function() {

  window.addEventListener("load", function() {
    var canvas, dataAttr, svg;
    canvas = d3.select("#canvas1");
    svg = canvas.append("svg").attr("width", 200).attr("height", 200);
    dataAttr = [
      {
        key1: 0,
        key2: 0,
        key3: 160,
        key4: 18,
        key5: "blue"
      }, {
        key1: 0,
        key2: 20,
        key3: 170,
        key4: 18,
        key5: "blue"
      }, {
        key1: 0,
        key2: 40,
        key3: 140,
        key4: 18,
        key5: "blue"
      }, {
        key1: 0,
        key2: 60,
        key3: 150,
        key4: 18,
        key5: "blue"
      }, {
        key1: 0,
        key2: 80,
        key3: 80,
        key4: 18,
        key5: "blue"
      }
    ];
    return svg.selectAll("rect").data(dataAttr).enter().append("rect").attr("x", function(d, i) {
      return d.key1;
    }).attr("y", function(d, i) {
      return d.key2;
    }).attr("width", function(d, i) {
      return d.key3;
    }).attr("height", function(d, i) {
      return d.key4;
    }).attr("fill", function(d, i) {
      return d.key5;
    });
  }, false);

}).call(this);
